# Generated by Django 6.0 on 2025-12-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'የተጨመረ ገንዘብ'), ('withdrawal', 'የተወጣ ገንዘብ'), ('game_entry', 'የጨዋታ መግቢያ ክፍያ'), ('prize_win', 'የሽልማት ገንዘብ'), ('admin_fee', 'የአስተዳዳሪ ክፍያ'), ('card_purchase', 'የቢንጎ ካርድ ግዢ'), ('refund', 'ገንዘብ መመለስ')], max_length=20),
        ),
    ]
