# Generated by Django 5.2.9 on 2025-12-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_game_transaction_game_round_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='completed_at',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'በመጠባበቅ ላይ'), ('completed', 'ተጠናቅቋል'), ('failed', 'አልተሳካም')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'የተጨመረ ገንዘብ'), ('withdrawal', 'የተወጣ ገንዘብ'), ('bet', 'የጨዋታ እርማት'), ('win', 'የሽልማት ገንዘብ'), ('refund', 'ገንዘብ መመለስ'), ('admin_fee', 'የአስተዳዳሪ ክፍያ')], max_length=20),
        ),
    ]
