# Generated by Django 5.2.9 on 2025-12-27 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('telebirr', 'ስልክ ብር (TeleBirr)'), ('cbe_birr', 'ኢ.ብ (CBE Birr)'), ('bank', 'ባንክ አቅርቦት'), ('awash', 'አዋሽ ባንክ'), ('dashen', 'ዳሸን ባንክ'), ('boa', 'ብ.ኦ.አ (Bank of Abyssinia)'), ('abyssinia', 'አቢሲንያ ባንክ'), ('hibret', 'ህብረት ባንክ')], max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'የክፍያ አካውንት',
                'verbose_name_plural': 'የክፍያ አካውንቶች',
                'ordering': ['payment_method', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'በመጠበቅ ላይ'), ('approved', 'ተፈቅዷል'), ('rejected', 'ውድቅ ተደርጓል'), ('processed', 'ተካሂዷል')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'የገንዘብ ማውጣት ጥያቄ',
                'verbose_name_plural': 'የገንዘብ ማውጣት ጥያቄዎች',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at'], 'verbose_name': 'አስገባት', 'verbose_name_plural': 'አስገባቶች'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'ግብይት', 'verbose_name_plural': 'ግብይቶች'},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_294647_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_game_ro_b99a75_idx',
        ),
        migrations.RemoveIndex(
            model_name='wallet',
            name='wallet_user_id_504f58_idx',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='game_round',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.AddField(
            model_name='deposit',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'በመጠበቅ ላይ'), ('approved', 'ተፈቅዷል'), ('rejected', 'ውድቅ ተደርጓል')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'በመጠበቅ ላይ'), ('completed', 'ተጠናቅቋል'), ('failed', 'አልተሳካም'), ('cancelled', 'ተሰርዟል')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'አስገባት'), ('withdraw', 'ውጣ'), ('withdraw_request', 'የገንዘብ ማውጣት ጥያቄ'), ('refund', 'መመለስ'), ('prize_win', 'ሽልማት'), ('game_play', 'ጨዋታ')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wallet',
            table=None,
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='transactions.paymentaccount'),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='payment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='transactions.paymentaccount'),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
