# Generated by Django 5.2.9 on 2025-12-27 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_paymentaccount_withdrawrequest_alter_deposit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentaccount',
            options={'ordering': ['payment_method', 'account_name'], 'verbose_name': 'Payment Account', 'verbose_name_plural': 'Payment Accounts'},
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='payment_method',
            field=models.CharField(choices=[('telebirr', 'TeleBirr'), ('cbe_birr', 'CBE Birr'), ('bank', 'Bank Transfer'), ('awash', 'Awash Bank'), ('dashen', 'Dashen Bank'), ('boa', 'Bank of Abyssinia'), ('abyssinia', 'Abyssinia Bank'), ('hibret', 'Hibret Bank')], max_length=50),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_accounts', to='transactions.agent'),
        ),
    ]
