# Generated by Django 5.2.9 on 2025-12-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_remove_callednumber_called_numb_called__3f26b9_idx_and_more'),
        ('transactions', '0008_alter_paymentaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='game_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_round', to='bingo.gameround'),
        ),
    ]
