# Generated by Django 5.2.9 on 2025-12-28 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_reference'),
        ('users', '0003_agent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_accounts', to='users.agent'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
