# Generated by Django 5.2.9 on 2025-12-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_paymentaccount_agent'),
        ('users', '0006_rename_agenttelegramlink_agentbotlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_accounts', to='users.agent'),
        ),
    ]
