# Generated by Django 5.2.9 on 2025-12-23 04:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveIntegerField(unique=True)),
                ('numbers', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bingo_cards',
                'indexes': [models.Index(fields=['card_number'], name='bingo_cards_card_nu_b3e0f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('total_stake', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('winning_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('called_numbers', models.JSONField(default=list)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('selection_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('winning_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.bingocard')),
            ],
            options={
                'db_table': 'game_rounds',
            },
        ),
        migrations.CreateModel(
            name='CalledNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(75)])),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='called_numbers_rel', to='bingo.gameround')),
            ],
            options={
                'db_table': 'called_numbers',
                'ordering': ['called_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_numbers', models.JSONField(default=list)),
                ('marked_positions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bingo_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingocard')),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='bingo.gameround')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_selections',
            },
        ),
        migrations.AddIndex(
            model_name='gameround',
            index=models.Index(fields=['status'], name='game_rounds_status_74e428_idx'),
        ),
        migrations.AddIndex(
            model_name='gameround',
            index=models.Index(fields=['round_number'], name='game_rounds_round_n_3df075_idx'),
        ),
        migrations.AddIndex(
            model_name='callednumber',
            index=models.Index(fields=['game_round'], name='called_numb_game_ro_8883ac_idx'),
        ),
        migrations.AddIndex(
            model_name='callednumber',
            index=models.Index(fields=['called_at'], name='called_numb_called__3f26b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='callednumber',
            unique_together={('game_round', 'number')},
        ),
        migrations.AddIndex(
            model_name='playerselection',
            index=models.Index(fields=['game_round', 'player'], name='player_sele_game_ro_c4d856_idx'),
        ),
        migrations.AddIndex(
            model_name='playerselection',
            index=models.Index(fields=['game_round', 'bingo_card'], name='player_sele_game_ro_dbd313_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerselection',
            unique_together={('game_round', 'bingo_card')},
        ),
    ]
