# Generated by Django 5.2.9 on 2025-12-25 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='callednumber',
            name='called_numb_called__3f26b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameround',
            name='game_rounds_status_74e428_idx',
        ),
        migrations.RemoveIndex(
            model_name='gameround',
            name='game_rounds_round_n_3df075_idx',
        ),
        migrations.AddIndex(
            model_name='callednumber',
            index=models.Index(fields=['game_round', 'called_at'], name='called_numb_game_ro_6bcf28_idx'),
        ),
        migrations.AddIndex(
            model_name='gameround',
            index=models.Index(fields=['status', 'round_number'], name='game_rounds_status_c39957_idx'),
        ),
        migrations.AddIndex(
            model_name='gameround',
            index=models.Index(fields=['status', 'selection_end_time'], name='game_rounds_status_f0326c_idx'),
        ),
        migrations.AddIndex(
            model_name='playerselection',
            index=models.Index(fields=['player', 'is_active'], name='player_sele_player__d59318_idx'),
        ),
    ]
