# Generated by Django 5.2.9 on 2025-12-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_remove_callednumber_called_numb_called__3f26b9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerselection',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
    ]
