# Generated by Django 5.2.9 on 2025-12-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_type_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
