# Generated by Django 5.2.9 on 2025-12-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegrambot_agentbotlink_telegramuser_botmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentBotLink',
            new_name='AgentTelegramLink',
        ),
    ]
