# Generated by Django 5.2.9 on 2025-12-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_agentbotlink_agenttelegramlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentTelegramLink',
            new_name='AgentBotLink',
        ),
    ]
