# Generated by Django 5.2.9 on 2025-12-30 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_agenttelegramlink_agentbotlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palyer_agent', to='users.agent'),
        ),
    ]
