# Generated by Django 5.2.9 on 2025-12-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='agent_referral_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
